/*
 * File: app/controller/Controller.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.Controller', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "button#btnMenuArrivals": {
                tap: 'onMenuArrivalsButtonTap'
            },
            "button#btnArrivals": {
                tap: 'onSelectArrivalsButtonTap'
            },
            "button#btnDepartures": {
                tap: 'onSelectDeparturesButtonTap'
            },
            "#lstArribos": {
                itemtap: 'onArrivalsListTap'
            },
            "#btnBackDetals": {
                tap: 'onBackDetailsButtonTap'
            },
            "#lstPartidas": {
                itemtap: 'onDeparturesListTap'
            }
        }
    },

    onMenuArrivalsButtonTap: function(button, e, eOpts) {

        var c = Ext.getCmp('menu');
        if(c === undefined){
            c = Ext.create('Aeropuerto.view.Menu');
            Ext.Viewport.add(c);
        }
        c.show({type:'slideIn', direction:'right', duration:70});

        var f =Ext.Viewport.getActiveItem();

        //Ext.Viewport.toggleMenu('right');
        //Ext.Viewport.setActiveItem(c, {type:'slide'});


    },

    onSelectArrivalsButtonTap: function(button, e, eOpts) {
        // Show or hide sliding menu:				var settingsPanel = Ext.getCmp('sliding_menu');
        /* var c = Ext.getCmp('menu');

        					        //if (settingsPanel.isHidden()) {
        					        //    settingsPanel.show({type:'slideIn', direction:'right', duration:70});
        					      //  } else {
        					           c.hide({type: 'slideOut', direction: 'left', duration: 70});
        var c = Ext.getCmp('arrivals');
        if(c === undefined) {
            c = Ext.create('Aeropuerto.view.Arrivals');
             Ext.Viewport.add(c);
        }

                c.show({type:'slideIn', direction:'left', duration:70});
        Ext.Viewport.setActiveItem(c); */

        Ext.getCmp('navigation').hide({type: 'slideOut', direction: 'left', duration: 70});
        var c = Ext.getCmp('main-toolbar');
        var p = Ext.getCmp('lstPartidas');
        p.hide();
        var a = Ext.getCmp('lstArribos');
        a.show();
        c.setTitle('Arribos');

        Aeropuerto.app.getController('Global').getArrivals();
    },

    onSelectDeparturesButtonTap: function(button, e, eOpts) {
        // Show or hide sliding menu:				var settingsPanel = Ext.getCmp('sliding_menu');
        /* var c = Ext.getCmp('menu');
         c.hide({type: 'slideOut', direction: 'left', duration: 70});
        var d = Ext.getCmp('departures');
                if(d === undefined){
                     d = Ext.create('Aeropuerto.view.Departures');
                    Ext.Viewport.add(d);
                }

                d.show({type:'slideIn', direction:'left', duration:70});
        Ext.Viewport.setActiveItem(d);*/

        Ext.getCmp('navigation').hide({type: 'slideOut', direction: 'left', duration: 70});
        var c = Ext.getCmp('main-toolbar');
        c.setTitle('Partidas');
        var p = Ext.getCmp('lstPartidas');
        p.show();
        var a = Ext.getCmp('lstArribos');
        a.hide();

        Aeropuerto.app.getController('Global').getDepartures();
    },

    onArrivalsListTap: function(dataview, index, target, record, e, eOpts) {
        this.goToDetails(dataview, index, target, record, e, eOpts);
    },

    onBackDetailsButtonTap: function(button, e, eOpts) {
        var c = Ext.getCmp('details');
        c.hide({type: 'slideOut', direction: 'right', duration: 120});
    },

    onDeparturesListTap: function(dataview, index, target, record, e, eOpts) {
        this.goToDetails(dataview, index, target, record, e, eOpts);
    },

    launch: function() {
                Aeropuerto.app.getController('Global').getArrivals();

    },

    goToDetails: function(dataview, index, target, record, e, eOpts) {
                var info;

                        if (record) {
                        var c = Ext.getCmp('details');
                        if(c === undefined){
                           alert("MUERTEEE");
                        }
                        //    c.setTitle("Vuelo");


                            // set the info
                            info = c.child('#info');
                            info.child('#photo').setData(record.data);
                           // info.child('#data').setData(record.data);

        //var se = Ext.Viewport.getActiveItem();
          //                  alert(se.id);
                            var p = Ext.getCmp('lstPartidas');
              //  p.hide();
                var a = Ext.getCmp('lstArribos');
              //  a.hide();
               //container.push(c);
                            c.show({type: 'slideIn', direction: 'left', duration: 120});
                        }
    }

});