/*
 * File: app/controller/Contacto.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.Contacto', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#btnContacto": {
                tap: 'onContactoTap'
            },
            "#containerContainerHome": {
                tap: 'contactioHomeButtonTap'
            }
        }
    },

    onContactoTap: function(button, e, eOpts) {
            Ext.Viewport.hideMenu('left');
            var tienda = Ext.getStore('UsuarioStore');
            this.getApplication().getController('LogicController').hideViewAll();
            if(tienda.getCount() > 0){
                Ext.getCmp('ContactoContainer').show();
            }else{
                alert('Iniciar secion ya');
                Aeropuerto.app.referrer = 'ContactoContainer';
                this.getApplication().getController('Usuarios').goToLogin();
            }
    },

    contactioHomeButtonTap: function(button, e, eOpts) {
           this.getApplication().getController('LogicController').showHideMenu('');
    }

});