/*
 * File: app/controller/Estacionamiento.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.Estacionamiento', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#estacionamientoContainerHome": {
                tap: 'onHomeButtonTap'
            },
            "#btnEstacionamiento": {
                tap: 'btnEstacionamiento'
            },
            "#seleccionarHoraComienzo": {
                tap: 'selectHoraTap'
            },
            "#seleccionarTiempoReserva": {
                tap: 'selectHoraTap1'
            },
            "#btnEstacionamientoContinuar": {
                tap: 'onEstacionamientoContinuar'
            },
            "#estacionamientoConfirmar": {
                tap: 'onEstacionamientoConfirmar'
            },
            "#estacionamientoCancelar": {
                tap: 'onEstacionamientoCancelar'
            }
        }
    },

    onHomeButtonTap: function(button, e, eOpts) {
           this.getApplication().getController('LogicController').showHideMenu('');
    },

    btnEstacionamiento: function(button, e, eOpts) {
        this.getApplication().getController('Global').checkLogged('EstacionamientoContainer');

    },

    selectHoraTap: function(button, e, eOpts) {
        Ext.getCmp('EstacionamientoHoraPicker').show();


    },

    selectHoraTap1: function(button, e, eOpts) {
        Ext.getCmp('EstacionamientoHoraPicker1').show();


    },

    onEstacionamientoContinuar: function(button, e, eOpts) {
         Ext.getCmp('estacionamientoForm').hide();
         Ext.getCmp('confirmarEstacionamientoForm').show();


    },

    onEstacionamientoConfirmar: function(button, e, eOpts) {
           Ext.Msg.alert( '', 'Se esta procesando su solicitud ');//Ext.getCmp('estacionamientoForm').
        Ext.getCmp('estacionamientoForm').show();
                 Ext.getCmp('confirmarEstacionamientoForm').hide();
    },

    onEstacionamientoCancelar: function(button, e, eOpts) {
        Ext.Msg.confirm("Cancelar", "Are you sure u want to cancel :( ?", function(btn){
            if (btn == 'yes'){
                Ext.getCmp('estacionamientoForm').show();
                Ext.getCmp('confirmarEstacionamientoForm').hide();
            }
        });
    }

});