/*
 * File: app/controller/Global.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.Global', {
    extend: 'Ext.app.Controller',

    config: {
        urlServer: 'http://audiodes.ddns.net/aicmobileservice/mobilews.asmx',
        urlWeather: 'http://api.worldweatheronline.com/free/v2/weather.ashx',
        weatherKey: '453edf069e02397083c3dcc4fe281'
    },

    getFlights: function(tipo, laTienda, parametros, mascara, panel) {
        console.log(mascara +' -- '+panel);

        Ext.Ajax.on('beforerequest', function(){
            if(mascara === '1'){
                // Ext.Viewport.mask({ xtype: 'loadmask' });
                //  Ext.getCmp(panel).mask({ xtype: 'loadmask' });
            }
        });


        Ext.Ajax.request({
            url: this.getUrlServer(),
            useDefaultXhrHeader: false,
            headers: {
                'Content-Type': 'text/xml; charset=utf-8',
                'SOAPAction': 'http://tempuri.org/' + tipo
            },
            method: 'POST',
            params: parametros,
            success: function(response) {
                var vuelos = response.responseXML.getElementsByTagName('Vuelo');
                var tienda = Ext.getStore(laTienda);
                tienda.getProxy().clear();
                tienda.data.clear();
                tienda.sync();
                Ext.each(vuelos, function(vuelo) {
                    tienda.addData(vuelo);
                    console.log(vuelo);
                }, this);
                tienda.sync();
                tienda.load();
            },
            failure: function(response) {
                alert('failure'+response.responseText);
                console.log(response.responseText);
            }
        });

        Ext.Ajax.on('requestcomplete', function(){
            if(mascara == '1'){
                // Ext.Viewport.unmask();
                Ext.getCmp(panel).unmask();
            }
        });

    },

    getDepartures: function(filtro, mascara, panel) {
        var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetDepartures xmlns="http://tempuri.org/"><filter>'+filtro+'</filter></GetDepartures></soap:Body></soap:Envelope>';
        this.getFlights('GetDepartures', 'Partidas', xmlParams,mascara,panel);
    },

    getArrivals: function(filtro, mascara, panel) {

        var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetArrivals xmlns="http://tempuri.org/"><filter>'+filtro+'</filter></GetArrivals></soap:Body></soap:Envelope>';
        this.getFlights('GetArrivals', 'Arribos', xmlParams,mascara,panel);
    },

    subscribe: function(uuid, flightNumber, timeStamp) {
        var plataforma = Ext.os.name;
        var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><Subscribe xmlns="http://tempuri.org/"><id>'+uuid+'</id><flightNumber>'+flightNumber+'</flightNumber><datetime>'+timeStamp+'</datetime><plataforma>'+plataforma+'</plataforma></Subscribe></soap:Body></soap:Envelope>';

        Ext.Ajax.request({
            url: this.getUrlServer(),
            useDefaultXhrHeader: false,
            headers: {
                'Content-Type': 'text/xml; charset=utf-8',
                'SOAPAction': 'http://tempuri.org/Subscribe'
            },
            method: 'POST',
            params: xmlParams,
            success: function(response) {
                Aeropuerto.app.getController('LogicController').changeSubscribeIcon();
            },
            failure: function(response) {
                alert('todo mal'+response.responseText);
                console.log(response.responseText);
            }
        });
        //this.getApplication().getController('LogicController').changeSubscribeIcon();

    },

    unSubscribe: function(uuid, flightNumber, timeStamp) {
           var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><UnSubscribe xmlns="http://tempuri.org/"><id>'+uuid+'</id><flightNumber>'+flightNumber+'</flightNumber><datetime>'+timeStamp+'</datetime></UnSubscribe></soap:Body></soap:Envelope>';

        Ext.Ajax.request({
                                            url: this.getUrlServer(),
                                            useDefaultXhrHeader: false,
                                            headers: {
                                                'Content-Type': 'text/xml; charset=utf-8',
                                                'SOAPAction': 'http://tempuri.org/UnSubscribe'
                                            },
                                            method: 'POST',
                                            params: xmlParams,
                                            success: function(response) {
                                                        Aeropuerto.app.getController('LogicController').changeSubscribeIcon();
                                            },
                                            failure: function(response) {
                                                alert('todo mal'+response.responseText);
                                                console.log(response.responseText);
                                            }
                                        });

    },

    getSubscriptions: function(container) {
        //Get and clear Susbscriptions

        var tienda = Ext.getStore('Suscripciones');
        tienda.getProxy().clear();
        tienda.data.clear();
        tienda.sync();
        var subs = Ext.getStore('MisVuelos');
        Ext.getCmp(container).mask({ xtype: 'loadmask' });

        for (i = 0; i < subs.getCount(); i++) {
            this.getFlight(subs.getAt(i).data.nVuelo,subs.getAt(i).data.fprogram);
        }
        Ext.getCmp(container).unmask();

    },

    getFlight: function(nVuelo, fprogram) {
        var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetFlight xmlns="http://tempuri.org/"><flight>'+nVuelo+'</flight><datetime>'+fprogram+'</datetime></GetFlight></soap:Body></soap:Envelope>';
        Ext.Ajax.request({
            url: this.getUrlServer(),
            useDefaultXhrHeader: false,
            headers: {
                'Content-Type': 'text/xml; charset=utf-8',
                'SOAPAction': 'http://tempuri.org/GetFlight'
            },
            method: 'POST',
            //async : false,
            params: xmlParams,
            success: function(response) {
                var vuelos = response.responseXML.getElementsByTagName('GetFlightResult');
                var tienda = Ext.getStore('Suscripciones');

                if(vuelos[0] === undefined){
                    Aeropuerto.app.getController('LogicController').deleteFlight(nVuelo,fprogram,Ext.getStore('Uuid').getAt(0).get('key'));
                }
                Ext.each(vuelos, function(vuelo) {
                    tienda.addData(vuelo);
                }, this);
                tienda.sync();
                tienda.load();
            },
            failure: function(response) {
                alert('todo mal'+response.responseText);
                console.log(response.responseText);
            }
        });
    },

    getVersion: function(cultura) {
        var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetCultureVersion xmlns="http://tempuri.org/"><pCultura>'+cultura+'</pCultura></GetCultureVersion></soap:Body></soap:Envelope>';

        Ext.Ajax.request({
            url: this.getUrlServer(),
            useDefaultXhrHeader: false,
            headers: {
                'Content-Type': 'text/xml; charset=utf-8',
                'SOAPAction': 'http://tempuri.org/GetCultureVersion'
            },
            method: 'POST',
            params: xmlParams,
            async : false,
            success: function(response) {
                var respuesta = response.responseXML.getElementsByTagName('GetCultureVersionResponse');

                Ext.each(respuesta, function(vuelo) {
                    version = vuelo.getElementsByTagName('GetCultureVersionResult')[0].firstChild.nodeValue;

                }, this);

                var tienda = Ext.getStore('StringsStore');
                if(tienda.getCount() > 0){
                    if(tienda.getAt(0).data.version !== version){
                        console.log('cambio version');
                        Aeropuerto.app.getController('Global').getTexts(cultura);
                    }else{
                        console.log('misma version');
                    }
                }else{
                    console.log('no tengo nadaaaa');
                    Aeropuerto.app.getController('Global').getTexts(cultura);
                }

            },
            failure: function(response) {
                alert('todo mal en get version'+response.responseText);
                console.log(response.responseText);
            }
        });
    },

    getTexts: function(cultura) {
                        var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetTexts xmlns="http://tempuri.org/"><pCultura>'+cultura+'</pCultura></GetTexts></soap:Body></soap:Envelope>';


                               Ext.Ajax.request({
                                                                    url: this.getUrlServer(),
                                                                    useDefaultXhrHeader: false,
                                                                    headers: {
                                                                        'Content-Type': 'text/xml; charset=utf-8',
                                                                        'SOAPAction': 'http://tempuri.org/GetTexts'
                                                                    },
                                                                    method: 'POST',
                                                                    params: xmlParams,
                                                                    async : false,
                                                                    success: function(response) {
                                                                    var vuelos = response.responseXML.getElementsByTagName('GetTextsResult');
                                                                    var tienda = Ext.getStore('StringsStore');
                                                                    tienda.getProxy().clear();
                                                                    tienda.data.clear();
                                                                    tienda.sync();
                                                                    Ext.each(vuelos, function(vuelo) {
                                                                        tienda.addData(vuelo);
                                                                        console.log(vuelo);
                                                                        console.log(tienda.getCount());

                                                                    }, this);
                                                                        console.log(tienda.getCount());
                                                                    },
                                                                    failure: function(response) {
                                                                        alert('todo mal'+response.responseText);
                                                                        console.log(response.responseText);
                                                                    }
                                                                });
    },

    getWeather: function(city) {
        var urlWeather = this.getUrlWeather();
        var weatherKey = this.getWeatherKey();
        var city = 'q='+city;

        var fill = '&format=xml&num_of_days=1&key=';

        var fullUrl = urlWeather +'?'+city+fill+weatherKey;

        var xmlHttp = null;
        xmlHttp = new XMLHttpRequest();
        xmlHttp.open( "GET", fullUrl, false );
        xmlHttp.send();
        /* console.log(fullUrl);
        console.log(xmlHttp.responseXML);
        console.log(xmlHttp.responseText); */
        var vuelos = xmlHttp.responseXML.getElementsByTagName('current_condition');

        var tienda = Ext.getStore('WeatherStore');
        tienda.getProxy().clear();
        tienda.data.clear();
        tienda.sync();
        Ext.each(vuelos, function(vuelo) {
            tienda.addData(vuelo);
        }, this);
        tienda.sync();
        tienda.load();
    },

    checkConnection: function() {

        if(!window.navigator.onLine){
            this.getApplication().getController('LogicController').hideViewAll();
            this.getApplication().getController('LogicController').showOffLine();
            throw new Error('No internet connection');

        }
    },

    checkLogged: function(referrer) {
        this.getApplication().getController('Global').checkConnection();

        //Aeropuerto.app.getApplication().getController('LogicController').showHideMenu('');
        Ext.Viewport.hideMenu('left');

        if(Ext.getStore('UsuarioStore').getCount() > 0){
            this.getApplication().getController('LogicController').hideViewAll();
            Ext.getCmp(referrer).show();
        }else{
            Ext.Msg.confirm("Iniciar sesion", "Necesita iniciar sesion", function(btn){
            if (btn == 'yes'){
                    Aeropuerto.app.getApplication().getController('LogicController').hideViewAll();
                    Aeropuerto.app.referrer = referrer;
                    Aeropuerto.app.getController('Usuarios').goToLogin();
            }
            });
        }
    }

});