/*
 * File: app/controller/Global.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.Global', {
    extend: 'Ext.app.Controller',

    config: {
        urlServer: 'http://audiodes.ddns.net/aicmobileservice/mobilews.asmx',
        urlWeather: 'http://api.worldweatheronline.com/free/v2/weather.ashx',
        weatherKey: '453edf069e02397083c3dcc4fe281'
    },

    getFlights: function(tipo, laTienda, parametros, mascara) {
        Ext.Ajax.on('beforerequest', function(){
        if(mascara == '0'){
                    Ext.Viewport.mask({ xtype: 'loadmask' });
        }
        });

        Ext.Ajax.request({
            url: this.getUrlServer(),
            useDefaultXhrHeader: false,
            headers: {
                'Content-Type': 'text/xml; charset=utf-8',
                'SOAPAction': 'http://tempuri.org/' + tipo
            },
            method: 'POST',
            params: parametros,
            success: function(response) {
                var vuelos = response.responseXML.getElementsByTagName('Vuelo');
                var tienda = Ext.getStore(laTienda);
                tienda.getProxy().clear();
                tienda.data.clear();
                tienda.sync();
                Ext.each(vuelos, function(vuelo) {
                    tienda.addData(vuelo);
                }, this);
                tienda.sync();
                tienda.load();
            },
            failure: function(response) {
                alert('failure'+response.responseText);
                console.log(response.responseText);
            }
        });

        Ext.Ajax.on('requestcomplete', function(){
            if(mascara == '0'){
                Ext.Viewport.unmask();
            }
        });
    },

    getDepartures: function(filtro, mascara) {
                    var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetDepartures xmlns="http://tempuri.org/"><filter>'+filtro+'</filter></GetDepartures></soap:Body></soap:Envelope>';
                    this.getFlights('GetDepartures', 'Partidas', xmlParams,mascara);
    },

    getArrivals: function(filtro, mascara) {

        var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetArrivals xmlns="http://tempuri.org/"><filter>'+filtro+'</filter></GetArrivals></soap:Body></soap:Envelope>';
        this.getFlights('GetArrivals', 'Arribos', xmlParams,mascara);
    },

    subscribe: function(uuid, flightNumber, timeStamp) {
            var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><Subscribe xmlns="http://tempuri.org/"><id>'+uuid+'</id><flightNumber>'+flightNumber+'</flightNumber><datetime>'+timeStamp+'</datetime><plataforma>Sencha</plataforma></Subscribe></soap:Body></soap:Envelope>';

        Ext.Ajax.request({
                                            url: this.getUrlServer(),
                                            useDefaultXhrHeader: false,
                                            headers: {
                                                'Content-Type': 'text/xml; charset=utf-8',
                                                'SOAPAction': 'http://tempuri.org/Subscribe'
                                            },
                                            method: 'POST',
                                            params: xmlParams,
                                            success: function(response) {
                                                //algo??
                                            },
                                            failure: function(response) {
                                                alert('todo mal'+response.responseText);
                                                console.log(response.responseText);
                                            }
                                        });
        this.getApplication().getController('LogicController').changeSubscribeIcon();

    },

    unSubscribe: function(uuid, flightNumber, timeStamp) {
           var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><UnSubscribe xmlns="http://tempuri.org/"><id>'+uuid+'</id><flightNumber>'+flightNumber+'</flightNumber><datetime>'+timeStamp+'</datetime></UnSubscribe></soap:Body></soap:Envelope>';

        Ext.Ajax.request({
                                            url: this.getUrlServer(),
                                            useDefaultXhrHeader: false,
                                            headers: {
                                                'Content-Type': 'text/xml; charset=utf-8',
                                                'SOAPAction': 'http://tempuri.org/UnSubscribe'
                                            },
                                            method: 'POST',
                                            params: xmlParams,
                                            success: function(response) {
                                            },
                                            failure: function(response) {
                                                alert('todo mal'+response.responseText);
                                                console.log(response.responseText);
                                            }
                                        });

                                                 this.getApplication().getController('LogicController').changeSubscribeIcon("subscribe");


    },

    getSubscriptions: function(uuid) {
        //Get and clear Susbscriptions

        var tienda = Ext.getStore('Suscripciones');
        tienda.getProxy().clear();
        tienda.data.clear();
        tienda.sync();
        var subs = Ext.getStore('MisVuelos');

        for (i = 0; i < subs.getCount(); i++) {
            this.getFlight(subs.getAt(i).data.nVuelo,subs.getAt(i).data.fprogram);
        }
    },

    getFlight: function(nVuelo, fprogram) {
        var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetFlight xmlns="http://tempuri.org/"><flight>'+nVuelo+'</flight><datetime>'+fprogram+'</datetime></GetFlight></soap:Body></soap:Envelope>';
               Ext.Ajax.request({
                                                    url: this.getUrlServer(),
                                                    useDefaultXhrHeader: false,
                                                    headers: {
                                                        'Content-Type': 'text/xml; charset=utf-8',
                                                        'SOAPAction': 'http://tempuri.org/GetFlight'
                                                    },
                                                    method: 'POST',
                                                    params: xmlParams,
                                                    success: function(response) {
                                                    var vuelos = response.responseXML.getElementsByTagName('GetFlightResult');
                                                    var tienda = Ext.getStore('Suscripciones');
                                                    Ext.each(vuelos, function(vuelo) {
                                                        tienda.addData(vuelo);
                                                        }, this);
                                                    tienda.sync();
                                                    tienda.load();
                                                    },
                                                    failure: function(response) {
                                                        alert('todo mal'+response.responseText);
                                                        console.log(response.responseText);
                                                    }
                                                });
    },

    getWeather: function(city) {
            var urlWeather = this.getUrlWeather();
            var weatherKey = this.getWeatherKey();
            var city = 'q='+city;

            var fill = '&format=xml&num_of_days=1&key=';

            var fullUrl = urlWeather +'?'+city+fill+weatherKey;

            var xmlHttp = null;
            xmlHttp = new XMLHttpRequest();
            xmlHttp.open( "GET", fullUrl, false );
            xmlHttp.send( null );

        var vuelos = xmlHttp.responseXML.getElementsByTagName('current_condition');

                        var tienda = Ext.getStore('WeatherStore');
                        tienda.getProxy().clear();
                        tienda.data.clear();
                        tienda.sync();
                        Ext.each(vuelos, function(vuelo) {
                            tienda.addData(vuelo);
                        }, this);
                        tienda.sync();
                        tienda.load();

    }

});