/*
 * File: app/controller/Home.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.Home', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#homeButtonBuscar": {
                tap: 'onhomeButtonBuscar'
            },
            "#btnHome": {
                tap: 'onHomeButtonTap'
            },
            "#homeContainerSubs": {
                tap: 'btnSubsHome'
            },
            "#homeContainerHome": {
                tap: 'onMenuButtonTap'
            },
            "#lstArribosHome": {
                itemtap: 'onArribosListTap'
            },
            "#lstPartidasHome": {
                itemtap: 'onPartidasListTap'
            },
            "#lstSubscriptions2": {
                itemtap: 'onSubsList'
            }
        }
    },

    onhomeButtonBuscar: function(button, e, eOpts) {
        Ext.getCmp('homeTabPanel').mask({ xtype: 'loadmask' });

        if(Ext.getCmp('homeTabPanel').getActiveItem().getId() === 'homePanelArribos'){
            Ext.getCmp('lstArribosHome').setScrollable(true);
            this.getApplication().getController('Global').getArrivals(Ext.getCmp('lblHomeBuscarVuelos').getValue(),1,'homeTabPanel');
        }
        else{
            Ext.getCmp('lstPartidasHome').setScrollable(true);
            this.getApplication().getController('Global').getDepartures(Ext.getCmp('lblHomeBuscarVuelos').getValue(),1,'homeTabPanel');
        }
    },

    onHomeButtonTap: function(button, e, eOpts) {
            Aeropuerto.app.getApplication().getController('LogicController').showHideMenu('');
            Ext.Viewport.hideMenu('left');
            this.getApplication().getController('LogicController').hideViewAll();

                var tienda = Ext.getStore('Arribos');
                tienda.getProxy().clear();
                tienda.data.clear();
                tienda.sync();
                tienda = Ext.getStore('Partidas');
                tienda.getProxy().clear();
                tienda.data.clear();
                tienda.sync();
                Ext.getCmp('lstArribosHome').setScrollable(false);
                Ext.getCmp('lstPartidasHome').setScrollable(false);

                Ext.getCmp('lstArribosHome').refresh();
                Ext.getCmp('lstPartidasHome').refresh();

            if(Ext.getStore('UsuarioStore').getCount() > 0){
                Ext.getCmp('homeContainerSubs').show();
            }else{
                Ext.getCmp('homeContainerSubs').hide();
            }

            Ext.getCmp('HomeContainer').show();

    },

    btnSubsHome: function(button, e, eOpts) {

        if(Ext.Viewport.getMenus().right.isHidden()){
            Ext.Viewport.showMenu('right');
            this.getApplication().getController('LogicController').beforeSubscriptions();
        }
        else
        {
            Ext.Viewport.hideMenu('right');
        }


    },

    onMenuButtonTap: function(button, e, eOpts) {
        this.getApplication().getController('LogicController').showHideMenu("");
    },

    onArribosListTap: function(dataview, index, target, record, e, eOpts) {

        Aeropuerto.app.referrer = 'HomeContainer';
        this.getApplication().getController('LogicController').goToDetails(dataview, index, target, record, e, eOpts);
    },

    onPartidasListTap: function(dataview, index, target, record, e, eOpts) {
        Aeropuerto.app.referrer = 'HomeContainer';
        this.getApplication().getController('LogicController').goToDetails(dataview, index, target, record, e, eOpts);
    },

    onSubsList: function(dataview, index, target, record, e, eOpts) {
                Aeropuerto.app.referrer = 'HomeContainer';
                this.getApplication().getController('LogicController').goToDetails(dataview, index, target, record, e, eOpts);
                Ext.Viewport.hideMenu('right');
    }

});