/*
 * File: app/controller/Lavado.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.Lavado', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.MessageBox'
    ],

    config: {
        control: {
            "#lavadoContainerHome": {
                tap: 'onHomeButtonTap'
            },
            "#btnLavado": {
                tap: 'btnLavadoTap'
            },
            "#selecLavadoHoraComienzo": {
                tap: 'selectHoraTap'
            },
            "#btnLavadoContinuar": {
                tap: 'onLavadoContinuar'
            },
            "#lavadoConfirmar": {
                tap: 'onLavadoConfirmar'
            },
            "#lavadoCancelar": {
                tap: 'onLavadoCancelar'
            }
        }
    },

    onHomeButtonTap: function(button, e, eOpts) {
           this.getApplication().getController('LogicController').showHideMenu('');
    },

    btnLavadoTap: function(button, e, eOpts) {
        this.getApplication().getController('Global').checkLogged('LavadoContainer');

    },

    selectHoraTap: function(button, e, eOpts) {
        Ext.getCmp('LavadoHoraPicker').show();


    },

    onLavadoContinuar: function(button, e, eOpts) {
         Ext.getCmp('lavadoForm').hide();
         Ext.getCmp('confirmarLavadoForm').show();


    },

    onLavadoConfirmar: function(button, e, eOpts) {
        Ext.Msg.alert( '', 'Se esta procesando su solicitud ');
        Ext.getCmp('lavadoForm').show();
        Ext.getCmp('confirmarLavadoForm').hide();
    },

    onLavadoCancelar: function(button, e, eOpts) {
        Ext.Msg.confirm("Cancelar", "Are you sure u want to cancel :( ?", function(btn){
          if (btn == 'yes'){
              Ext.getCmp('lavadoForm').show();
              Ext.getCmp('confirmarLavadoForm').hide();
          }
        });

    }

});