/*
 * File: app/controller/LogicController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.LogicController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#btnSubscriptions": {
                tap: 'btnSubscriptionsTap'
            },
            "#btnVuelos": {
                tap: 'btnVuelosTap'
            },
            "#homeContainerSubs": {
                tap: 'btnSubsHome'
            },
            "#vuelosContainerHome": {
                tap: 'onVuelosButtonTap'
            },
            "#lstArribos": {
                itemtap: 'onArribosListTap'
            },
            "#btnDetailsBack": {
                tap: 'onDetailsBackButtonTap'
            },
            "#lstPartidas": {
                itemtap: 'onPartidasListItemTap'
            },
            "#btnDetailsSubscribe": {
                tap: 'onDetailsSubscribeButtonTap'
            },
            "#lstSubscriptions": {
                itemtap: 'onSuscripcionesListItemTap'
            },
            "#txtFiltro": {
                change: 'onTextfieldChange'
            },
            "#homeContainerHome": {
                tap: 'onMenuButtonTap'
            },
            "#suscripcionesContainerHome": {
                tap: 'onSuscripcionesHomeButtonTap'
            },
            "#btnDetailsRefresh": {
                tap: 'onDetailsRefresh'
            },
            "#btnOffLine": {
                tap: 'btnOffLine'
            },
            "#btnHome": {
                tap: 'onHomeButtonTap'
            }
        }
    },

    btnSubscriptionsTap: function(button, e, eOpts) {

        Ext.Viewport.hideMenu('left');
        this.getApplication().getController('Global').checkConnection();

        this.hideViewAll();
        this.showView('SuscripcionesContainer');

        this.getApplication().getController('Global').getSubscriptions('SuscripcionesContainer');

        Aeropuerto.app.referrer = 'SuscripcionesContainer';

    },

    btnVuelosTap: function(button, e, eOpts) {
            Aeropuerto.app.getApplication().getController('LogicController').showHideMenu('');
            Ext.Viewport.hideMenu('left');
            this.getApplication().getController('LogicController').hideViewAll();
            Ext.getCmp('VuelosContainer').show();
            Aeropuerto.app.referrer = 'VuelosContainer';

        this.getApplication().getController('Global').checkConnection();


        this.getApplication().getController('Global').getArrivals('','0');

    },

    btnSubsHome: function(button, e, eOpts) {

        if(Ext.Viewport.getMenus().right.isHidden()){
            Ext.Viewport.showMenu('right');
            this.getApplication().getController('Global').getSubscriptions('suscripcionesMenu');
            console.log(Ext.getCmp('lstSubscriptions2').itemsCount);
        }
        else
        {
            Ext.Viewport.hideMenu('right');
        }


    },

    onVuelosButtonTap: function(button, e, eOpts) {
        this.showHideMenu("");
    },

    onArribosListTap: function(dataview, index, target, record, e, eOpts) {

        this.goToDetails(dataview, index, target, record, e, eOpts);
    },

    onDetailsBackButtonTap: function(button, e, eOpts) {
                this.hideViewAll();
                this.showView(Aeropuerto.app.referrer);
    },

    onPartidasListItemTap: function(dataview, index, target, record, e, eOpts) {
          this.goToDetails(dataview, index, target, record, e, eOpts);
    },

    onDetailsSubscribeButtonTap: function(button, e, eOpts) {
        this.getApplication().getController('Global').checkConnection();
        var icon = Ext.getCmp('btnDetailsSubscribe');
        var store= Ext.getStore('Uuid');
        var uuid = store.getAt(0).get('key');
        var c = Ext.getCmp('companyName').getData();

        var vuelos = Ext.getStore('MisVuelos');
        var susc = Ext.getStore('Suscripciones');
        var list = Ext.getCmp('lstSubscriptions');
        if (icon.getIconCls() === 'favorites') {
           this.getApplication().getController('Global').subscribe(uuid,c.nVuelo,c.fprogram);
            vuelos.add({'nVuelo' : c.nVuelo,'fprogram': c.fprogram});
                 vuelos.sync();
        }
        else
        {
            this.getApplication().getController('Global').unSubscribe(uuid,c.nVuelo,c.fprogram);


            for (i = 0; i < vuelos.getCount(); i++) {
                 if(vuelos.getAt(i).data.nVuelo == c.nVuelo && vuelos.getAt(i).data.fprogram == c.fprogram){
                        var index =  i;
                 }
            }
                for (i = 0; i < susc.getCount(); i++) {
                 if(susc.getAt(i).data.nVuelo == c.nVuelo && susc.getAt(i).data.fprogram == c.fprogram){
                        var index2 =  i;
                 }
            }
            vuelos.removeAt(index);
            vuelos.sync();
            susc.removeAt(index2);
            susc.sync();

            list.refresh();

        }


    },

    onSuscripcionesListItemTap: function(dataview, index, target, record, e, eOpts) {
          this.goToDetails(dataview, index, target, record, e, eOpts);
    },

    onTextfieldChange: function(textfield, newValue, oldValue, eOpts) {
        var lstArrivals = Ext.getCmp('lstArribos');
        if(lstArrivals.isHidden()){

            this.getApplication().getController('Global').getDepartures(newValue);
        }
        else{
            this.getApplication().getController('Global').getArrivals(newValue);
        }
    },

    onMenuButtonTap: function(button, e, eOpts) {
        this.showHideMenu("");
    },

    onSuscripcionesHomeButtonTap: function(button, e, eOpts) {
        this.showHideMenu("");
    },

    onDetailsRefresh: function(button, e, eOpts) {
        this.getApplication().getController('Global').checkConnection();
            //se actualiza la lista de arribos o partidas dependiendo de lo que sea el vuelo seleccionado
            if(this.globalRecord.data.esArribo){
                this.getApplication().getController('Global').getArrivals('','0');
                var tienda =  Ext.getStore('Arribos');
                Ext.getCmp('lstArribos').refresh();
            }else{
                this.getApplication().getController('Global').getDepartures('','0');
                var tienda =  Ext.getStore('Partidas');
                Ext.getCmp('lstPartidas').refresh();

            }
            //se obtiene el vuelo de la lista actualizada
            for (i = 0; i < tienda.getCount(); i++) {
                 if(tienda.getAt(i).data.nVuelo == this.globalRecord.data.nVuelo){
                     var index =  i;
                 }
            }
            //se actualizan los datos
             Ext.getCmp('companyName').setData(tienda.getAt(index).data);

    },

    btnOffLine: function(button, e, eOpts) {
        if(window.navigator.onLine){
            Ext.getCmp('offLineContainer').hide();
            this.showView('mainView');
            this.btnArribos();
            var cultura = navigator.language;
            this.getApplication().getController('Global').getVersion(cultura);
            this.getApplication().getController('Global').getArrivals('','0');
        }
    },

    onHomeButtonTap: function(button, e, eOpts) {
            Aeropuerto.app.getApplication().getController('LogicController').showHideMenu('');
            Ext.Viewport.hideMenu('left');
            this.getApplication().getController('LogicController').hideViewAll();
            Ext.getCmp('HomeContainer').show();
    },

    createUuid: function() {
                 function s4() {
                    return Math.floor((1 + Math.random()) * 0x10000)
                               .toString(16)
                               .substring(1);
                  }
                  return function() {
                    return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
                           s4() + '-' + s4() + s4() + s4();
                  };
    },

    goToDetails: function(dataview, index, target, record, e, eOpts) {

        this.globalRecord = record;


        if (record) {

            // set the info
        Ext.getCmp('companyName').setData(record.data);

            var esMyVuelo =  Ext.getStore('MisVuelos');

            var index = esMyVuelo.find('nVuelo', record.data.nVuelo);

            if(index < 0){
                Ext.getCmp('btnDetailsSubscribe').setIconCls('favorites');
            }else{
                Ext.getCmp('btnDetailsSubscribe').setIconCls('trash');

            }

           this.getApplication().getController('LogicController').hideViewAll();
           Ext.getCmp('FlightDetailsContainer').show();
           this.showHideMenu('left');
           var tienda = Ext.getStore('WeatherStore');

            if(record.data.esArribo)
            {
                //Tiempo en el lugar de origen  Ext.Viewport.mask({ xtype: 'loadmask' });
                Ext.getCmp('detailsOrigen').setHtml(record.data.origen);
                Ext.getCmp('origen').mask({ xtype: 'loadmask' });
                Ext.getCmp('destino').mask({ xtype: 'loadmask' });
                this.getApplication().getController('Global').getWeather(record.data.origen);
                 Ext.getCmp('origen').setData(tienda.getAt(0).data);
                 Ext.getCmp('origen').unmask();
                //Tiempo en el lugar de destino (Montevideo)
                Ext.getCmp('detailsDestino').setHtml("Montevideo");
                this.getApplication().getController('Global').getWeather('Montevideo');
                 Ext.getCmp('destino').setData(tienda.getAt(0).data);
               Ext.getCmp('destino').unmask();

            }else
            {
                //Tiempo en el lugar de origen (Montevideo)
                Ext.getCmp('detailsOrigen').setHtml("Montevideo");
                this.getApplication().getController('Global').getWeather('Montevideo');
                 Ext.getCmp('origen').setData(tienda.getAt(0).data);
                //Tiempo en el lugar de destino
                Ext.getCmp('detailsDestino').setHtml(record.data.destino);
                this.getApplication().getController('Global').getWeather(record.data.destino);
                 Ext.getCmp('destino').setData(tienda.getAt(0).data);
            }

        }

    },

    detailsRefresh: function(dataview, index, target, record, e, eOpts) {
        console.log(this.globalRecord);

    },

    getTimeStamp: function() {
        //Return a timestamp with the format "yy-m-d h:MM:ss" ex. 2014-11-17 14:47:1


        // Create a date object with the current time
          var now = new Date();

        // Create an array with the current month, day and time
          var date = [ now.getFullYear(), now.getMonth() + 1, now.getDate() ];

        // Create an array with the current hour, minute and second
          var time = [ now.getHours(), now.getMinutes(), now.getSeconds() ];


        // Return the formatted string
          return date.join("-") + " " + time.join(":") ;
    },

    changeSubscribeIcon: function() {
        var c = Ext.getCmp('btnDetailsSubscribe');

        if (c.getIconCls() === 'favorites') {
        c.setIconCls('trash');
        }
        else
        {
        c.setIconCls('favorites');
        }
    },

    showHideMenu: function(referrer) {
        if(Ext.Viewport.getMenus().left.isHidden()){
            if(referrer === "" || referrer == "right")
                Ext.Viewport.showMenu('left');
        }
        else
        {
            if(referrer === "" || referrer == "left")
                Ext.Viewport.hideMenu('left');
        }
    },

    showView: function(view) {
        this.hideViewAll();
        Ext.getCmp(view).show();
    },

    hideViewAll: function() {
        /*
        Ext.getCmp('lstArribos').hide();
        Ext.getCmp('lstPartidas').hide();
        Ext.getCmp('lstSubscriptions').hide();
        Ext.getCmp('mainView').hide();
        Ext.getCmp('details').hide();

        */
        Ext.getCmp('userContainer').hide();
        Ext.getCmp('TaxiContainer').hide();
        Ext.getCmp('ServiciosContainer').hide();
        Ext.getCmp('NormasContainer').hide();

        Ext.getCmp('EstacionamientoContainer').hide();
        Ext.getCmp('LavadoContainer').hide();
        Ext.getCmp('ContactoContainer').hide();

        Ext.getCmp('HomeContainer').hide();
        Ext.getCmp('VuelosContainer').hide();
        Ext.getCmp('SuscripcionesContainer').hide();
        Ext.getCmp('FlightDetailsContainer').hide();
    },

    showOffLine: function() {
         /*

        var panel = Ext.create('Aeropuerto.view.offLineContainer');
        Ext.Viewport.add(panel);
        panel.show();
        */

        ///Ext.create('offLineContainer');
        this.hideViewAll();
        Ext.getCmp('offLineContainer').show();
    }

});