/*
 * File: app/controller/LogicController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.LogicController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#btnArribos": {
                tap: 'btnArribos'
            },
            "#btnPartidas": {
                tap: 'btnPartidas'
            },
            "#btnSubscriptions": {
                tap: 'btnSubscriptionsTap'
            },
            "#btnLogin": {
                tap: 'btnLogin'
            },
            "#lstArribos": {
                itemtap: 'onArribosListTap'
            },
            "#btnDetailsBack": {
                tap: 'onDetailsBackButtonTap'
            },
            "#lstPartidas": {
                itemtap: 'onPartidasListItemTap'
            },
            "#btnDetailsSubscribe": {
                tap: 'onDetailsSubscribeButtonTap'
            },
            "#lstSubscriptions": {
                itemtap: 'onSuscripcionesListItemTap'
            },
            "#txtFiltro": {
                change: 'onTextfieldChange'
            },
            "#btnMenu": {
                tap: 'onMenuButtonTap'
            },
            "#btnDetailsRefresh": {
                tap: 'onDetailsRefresh'
            },
            "#btnOffLine": {
                tap: 'btnOffLine'
            }
        }
    },

    btnArribos: function(button, e, eOpts) {
        Ext.Viewport.hideMenu('left');
        this.getApplication().getController('Global').checkConnection();

        //if(!window.navigator.onLine){
        //this.getApplication().getController('LogicController').hideViewAll();
        //this.getApplication().getController('LogicController').showOffLine();
        //    console.log("entro");
        //}else{

        this.getApplication().getController('Global').getArrivals('','0');

        var topBar = Ext.getCmp('topBar');
        topBar.setTitle(Ext.getStore('StringsStore').getAt(0).data.arribos);

        this.hideViewAll();
        this.showView('mainView');

        Ext.getCmp('lstArribos').show();
        //}

    },

    btnPartidas: function(button, e, eOpts) {
        Ext.Viewport.hideMenu('left');
        this.getApplication().getController('Global').checkConnection();
        var topBar = Ext.getCmp('topBar');
        topBar.setTitle(Ext.getStore('StringsStore').getAt(0).data.partidas);

        this.getApplication().getController('Global').getDepartures('','0');

        this.hideViewAll();
        this.showView('mainView');

        Ext.getCmp('lstPartidas').show();

    },

    btnSubscriptionsTap: function(button, e, eOpts) {
        Ext.Viewport.hideMenu('left');
        this.getApplication().getController('Global').checkConnection();
        var topBar = Ext.getCmp('topBar');
        topBar.setTitle(Ext.getStore('StringsStore').getAt(0).data.suscripciones);

        this.hideViewAll();
        this.showView('mainView');

        this.getApplication().getController('Global').getSubscriptions();

        Ext.getCmp('lstSubscriptions').show();

    },

    btnLogin: function(button, e, eOpts) {
        Ext.Viewport.hideMenu('left');
        this.getApplication().getController('Global').checkConnection();
        this.hideViewAll();
        Aeropuerto.app.referrer = '';
        this.getApplication().getController('Usuarios').goToLogin();
    },

    onArribosListTap: function(dataview, index, target, record, e, eOpts) {

        this.goToDetails(dataview, index, target, record, e, eOpts);
    },

    onDetailsBackButtonTap: function(button, e, eOpts) {
         var c = Ext.getCmp('details');
        var d = Ext.getCmp('mainView');
                c.hide();
                d.show();
    },

    onPartidasListItemTap: function(dataview, index, target, record, e, eOpts) {
          this.goToDetails(dataview, index, target, record, e, eOpts);
    },

    onDetailsSubscribeButtonTap: function(button, e, eOpts) {
        this.getApplication().getController('Global').checkConnection();
        var icon = Ext.getCmp('details').child('#tbDetails').child('#btnDetailsSubscribe');
        var store= Ext.getStore('Uuid');
        var uuid = store.getAt(0).get('key');
        var c = Ext.getCmp('details').child('#flightDetails').child('#companyName').getData();

        var vuelos = Ext.getStore('MisVuelos');
        var susc = Ext.getStore('Suscripciones');
        var list = Ext.getCmp('lstSubscriptions');
        if (icon.getIconCls() === 'favorites') {
           this.getApplication().getController('Global').subscribe(uuid,c.nVuelo,c.fprogram);
            vuelos.add({'nVuelo' : c.nVuelo,'fprogram': c.fprogram});
                 vuelos.sync();
        }
        else
        {
            this.getApplication().getController('Global').unSubscribe(uuid,c.nVuelo,c.fprogram);


            for (i = 0; i < vuelos.getCount(); i++) {
                 if(vuelos.getAt(i).data.nVuelo == c.nVuelo && vuelos.getAt(i).data.fprogram == c.fprogram){
                        var index =  i;
                 }
            }
                for (i = 0; i < susc.getCount(); i++) {
                 if(susc.getAt(i).data.nVuelo == c.nVuelo && susc.getAt(i).data.fprogram == c.fprogram){
                        var index2 =  i;
                 }
            }
            vuelos.removeAt(index);
            vuelos.sync();
            susc.removeAt(index2);
            susc.sync();

            list.refresh();

        }


    },

    onSuscripcionesListItemTap: function(dataview, index, target, record, e, eOpts) {
          this.goToDetails(dataview, index, target, record, e, eOpts);
    },

    onTextfieldChange: function(textfield, newValue, oldValue, eOpts) {
        var lstArrivals = Ext.getCmp('lstArribos');
        if(lstArrivals.isHidden()){

            this.getApplication().getController('Global').getDepartures(newValue);
        }
        else{
            this.getApplication().getController('Global').getArrivals(newValue);
        }
    },

    onMenuButtonTap: function(button, e, eOpts) {
        this.showHideMenu("");
    },

    onDetailsRefresh: function(button, e, eOpts) {
        this.getApplication().getController('Global').checkConnection();
            //se actualiza la lista de arribos o partidas dependiendo de lo que sea el vuelo seleccionado
            if(this.globalRecord.data.esArribo){
                this.getApplication().getController('Global').getArrivals('','0');
                var tienda =  Ext.getStore('Arribos');
                Ext.getCmp('lstArribos').refresh();
            }else{
                this.getApplication().getController('Global').getDepartures('','0');
                var tienda =  Ext.getStore('Partidas');
                Ext.getCmp('lstPartidas').refresh();

            }
            //se obtiene el vuelo de la lista actualizada
            for (i = 0; i < tienda.getCount(); i++) {
                 if(tienda.getAt(i).data.nVuelo == this.globalRecord.data.nVuelo){
                     var index =  i;
                 }
            }
            //se actualizan los datos
             Ext.getCmp('companyName').setData(tienda.getAt(index).data);

    },

    btnOffLine: function(button, e, eOpts) {
        if(window.navigator.onLine){
            Ext.getCmp('offLineContainer').hide();
            this.showView('mainView');
            this.btnArribos();
            var cultura = navigator.language;
            this.getApplication().getController('Global').getVersion(cultura);
            this.getApplication().getController('Global').getArrivals('','0');
        }
    },

    createUuid: function() {
                 function s4() {
                    return Math.floor((1 + Math.random()) * 0x10000)
                               .toString(16)
                               .substring(1);
                  }
                  return function() {
                    return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
                           s4() + '-' + s4() + s4() + s4();
                  };
    },

    goToDetails: function(dataview, index, target, record, e, eOpts) {
        var info;
        this.globalRecord = record;

        var topBar = Ext.getCmp('tbDetails');
        topBar.setTitle(Ext.getStore('StringsStore').getAt(0).data.detalles);


        if (record) {
            var c = Ext.getCmp('details');
            if(c === undefined){
                alert("MUERTEEE");
            }

            // set the info
            info = c.child('#flightDetails');
            info.child('#companyName').setData(record.data);
            // info.child('#data').setData(record.data);

            var d = Ext.getCmp('mainView');

            var b = Ext.getCmp('details').child('#tbDetails').child('#btnDetailsSubscribe');

            var esMyVuelo =  Ext.getStore('MisVuelos');

            var index = esMyVuelo.find('nVuelo', record.data.nVuelo);

            if(index < 0){
                b.setIconCls('favorites');
            }else{
                b.setIconCls('trash');

            }
            d.hide();
            c.show();
            this.showHideMenu('left');
            var tienda = Ext.getStore('WeatherStore');

            if(record.data.esArribo)
            {
                //Tiempo en el lugar de origen  Ext.Viewport.mask({ xtype: 'loadmask' });
                Ext.getCmp('detailsOrigen').setHtml(record.data.origen);
                c.child('#weather').child('#origen').mask({ xtype: 'loadmask' });
                c.child('#weather').child('#destino').mask({ xtype: 'loadmask' });
                this.getApplication().getController('Global').getWeather(record.data.origen);
                c.child('#weather').child('#origen').setData(tienda.getAt(0).data);
                c.child('#weather').child('#origen').unmask();
                //Tiempo en el lugar de destino (Montevideo)
                Ext.getCmp('detailsDestino').setHtml("Montevideo");
                this.getApplication().getController('Global').getWeather('Montevideo');
                c.child('#weather').child('#destino').setData(tienda.getAt(0).data);
                c.child('#weather').child('#destino').unmask();

            }else
            {
                //Tiempo en el lugar de origen (Montevideo)
                Ext.getCmp('detailsOrigen').setHtml("Montevideo");
                this.getApplication().getController('Global').getWeather('Montevideo');
                c.child('#weather').child('#origen').setData(tienda.getAt(0).data);
                //Tiempo en el lugar de destino
                Ext.getCmp('detailsDestino').setHtml(record.data.destino);
                this.getApplication().getController('Global').getWeather(record.data.destino);
                c.child('#weather').child('#destino').setData(tienda.getAt(0).data);
            }

        }

    },

    detailsRefresh: function(dataview, index, target, record, e, eOpts) {
        console.log(this.globalRecord);

    },

    getTimeStamp: function() {
        //Return a timestamp with the format "yy-m-d h:MM:ss" ex. 2014-11-17 14:47:1


        // Create a date object with the current time
          var now = new Date();

        // Create an array with the current month, day and time
          var date = [ now.getFullYear(), now.getMonth() + 1, now.getDate() ];

        // Create an array with the current hour, minute and second
          var time = [ now.getHours(), now.getMinutes(), now.getSeconds() ];


        // Return the formatted string
          return date.join("-") + " " + time.join(":") ;
    },

    changeSubscribeIcon: function() {
        var c = Ext.getCmp('details').child('#tbDetails').child('#btnDetailsSubscribe');

        if (c.getIconCls() === 'favorites') {
        c.setIconCls('trash');
        }
        else
        {
        c.setIconCls('favorites');
        }
    },

    showHideMenu: function(referrer) {
        if(Ext.Viewport.getMenus().left.isHidden()){
            if(referrer === "" || referrer == "right")
                Ext.Viewport.showMenu('left');
        }
        else
        {
            if(referrer === "" || referrer == "left")
                Ext.Viewport.hideMenu('left');
        }
    },

    showView: function(view) {
        this.hideViewAll();
        Ext.getCmp(view).show();
    },

    hideViewAll: function() {
        Ext.getCmp('lstArribos').hide();
        Ext.getCmp('lstPartidas').hide();
        Ext.getCmp('lstSubscriptions').hide();
        Ext.getCmp('mainView').hide();
        Ext.getCmp('userContainer').hide();
        Ext.getCmp('TaxiContainer').hide();
        Ext.getCmp('EstacionamientoContainer').hide();
        Ext.getCmp('LavadoContainer').hide();
        Ext.getCmp('ContactoContainer').hide();
        Ext.getCmp('details').hide();


    },

    showOffLine: function() {
         /*

        var panel = Ext.create('Aeropuerto.view.offLineContainer');
        Ext.Viewport.add(panel);
        panel.show();
        */

        ///Ext.create('offLineContainer');
        this.hideViewAll();
        Ext.getCmp('offLineContainer').show();
    }

});