/*
 * File: app/controller/Servicios.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.Servicios', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#serviciosContainerHome": {
                tap: 'onHomeButtonTap'
            },
            "#btnServicios": {
                tap: 'btnServiciosTap'
            }
        }
    },

    onHomeButtonTap: function(button, e, eOpts) {
           this.getApplication().getController('LogicController').showHideMenu('');
    },

    btnServiciosTap: function(button, e, eOpts) {
            Aeropuerto.app.getApplication().getController('LogicController').showHideMenu('');
            Ext.Viewport.hideMenu('left');
            this.getApplication().getController('LogicController').hideViewAll();
            Ext.getCmp('ServiciosContainer').show();
    }

});