/*
 * File: app/controller/Usuarios.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.controller.Usuarios', {
    extend: 'Ext.app.Controller',

    config: {
        urlServer: 'http://audiodes.ddns.net/aicmobileservice/mobilews.asmx',

        control: {
            "#btnLoginInicial": {
                tap: 'onloginInicialButtonTap'
            },
            "#btnRegisterInicial": {
                tap: 'onRegisterInicialButtonTap'
            },
            "#userContainerHome": {
                tap: 'onHomeButtonTap'
            },
            "#btnRegister": {
                tap: 'onRegisterButtonTap'
            },
            "#trueLogin": {
                tap: 'onTrueLoginTap'
            },
            "#btnLogOut": {
                tap: 'onButtonLogOutTap'
            }
        }
    },

    onloginInicialButtonTap: function(button, e, eOpts) {
            var a = Ext.getCmp('loginForm');
            var b = Ext.getCmp('initial');

        Ext.getCmp('userContainerHome').setIconCls('arrow_left');

            a.show();
            b.hide();
    },

    onRegisterInicialButtonTap: function(button, e, eOpts) {
                            var a = Ext.getCmp('registerForm');
                            var b = Ext.getCmp('initial');

        Ext.getCmp('userContainerHome').setIconCls('arrow_left');

                            a.show();
                            b.hide();
    },

    onHomeButtonTap: function(button, e, eOpts) {
            if(Ext.getCmp('initial').isHidden()){
                var a = Ext.getCmp('loginForm');
                var b = Ext.getCmp('registerForm');
                var c = Ext.getCmp('initial');
                Ext.getCmp('userContainerHome').setIconCls('list');
                a.hide();
                b.hide();
                c.show();
            }else{

               this.getApplication().getController('LogicController').showHideMenu('');
            }
    },

    onRegisterButtonTap: function(button, e, eOpts) {
        this.createUser(Ext.getCmp('registerName').getValue(),Ext.getCmp('registerLastName').getValue(),Ext.getCmp('registerDate').getValue('d/m/Y'),Ext.getCmp('registerPassword').getValue(),Ext.getCmp('registerEmail').getValue(),'');
    },

    onTrueLoginTap: function(button, e, eOpts) {
        this.userLogin(Ext.getCmp('loginUsername').getValue(),Ext.getCmp('loginPassword').getValue());
    },

    onButtonLogOutTap: function(button, e, eOpts) {
        var tienda = Ext.getStore('UsuarioStore');
        tienda.getProxy().clear();
        tienda.data.clear();
        tienda.sync();

        this.goToLogin();
    },

    createUser: function(nombre, apellido, fnacimiento, contrasena, email, nacionalidad) {
        var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><CreateUser xmlns="http://tempuri.org/"><pEmail>'+email+'</pEmail><pNombre>'+nombre+'</pNombre><pApellido>'+apellido+'</pApellido><pPassword>'+contrasena+'</pPassword><pFNac>'+fnacimiento+'</pFNac><pNacionalidad>'+nacionalidad+'</pNacionalidad></CreateUser></soap:Body></soap:Envelope>';
        Ext.Ajax.request({
                                            url: this.getUrlServer(),
                                            useDefaultXhrHeader: false,
                                            headers: {
                                                'Content-Type': 'text/xml; charset=utf-8',
                                                'SOAPAction': 'http://tempuri.org/CreateUser'
                                            },
                                            method: 'POST',
                                            params: xmlParams,
                                            success: function(response) {
                                                alert('Usuario creado');
                                                var tienda = Ext.getStore('UsuarioStore');
                                                console.log(tienda.getCount());
                                                tienda.add({nombre : nombre,apellido:apellido,fnac : fnacimiento,email :email,password:contrasena,nacionalidad:nacionalidad});
                                                tienda.sync();
                                                tienda.load();
                                                console.log(tienda.getCount());
                                                console.log(tienda.getAt(0).data);
                                                Aeropuerto.app.getController('Usuarios').goToLogin();
                                            },
                                            failure: function(response) {
                                                alert('todo mal'+response.responseText);
                                                console.log(response.responseText);
                                            }
                                        });
    },

    userLogin: function(email, password) {
        var xmlParams = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><LogIn xmlns="http://tempuri.org/"><email>'+email+'</email><password>'+password+'</password></LogIn></soap:Body></soap:Envelope>';

        Ext.Ajax.request({
                                                    url: this.getUrlServer(),
                                                    useDefaultXhrHeader: false,
                                                    headers: {
                                                        'Content-Type': 'text/xml; charset=utf-8',
                                                        'SOAPAction': 'http://tempuri.org/LogIn'
                                                    },
                                                    method: 'POST',
                                                    params: xmlParams,
                                                    success: function(response) {

                                                          var tienda = Ext.getStore('UsuarioStore');
                                                           console.log(tienda.getCount());
                                                          var usuarios = response.responseXML.getElementsByTagName('LogInResponse');
                                                          Ext.each(usuarios, function(usuario) {
                                                                tienda.addData(usuario);
                                                                }, this);
                                                            if(tienda.getCount() > 0){
                                                                tienda.sync();
                                                                tienda.load();
                                                                alert('Login Correcto');
                                                           console.log(tienda.getCount());
                                                                console.log(tienda.getAt(0).data);
                                                                Aeropuerto.app.getController('Usuarios').goToLogin();
                                                            }else{
                                                                alert('Login Incorrecto');
                                                            }
                                                       console.log(response);

                                                    },
                                                    failure: function(response) {
                                                        alert(response.responseText);
                                                        console.log(response.responseText);
                                                    }
                                                });
    },

    goToLogin: function() {
            var userContainer = Ext.getCmp('userContainer');
            userContainer.show();

            var initial = Ext.getCmp('initial');
            var logged = Ext.getCmp('Logged');

            var tienda = Ext.getStore('UsuarioStore');
            if(tienda.getCount() > 0){
                logged.show();
                initial.hide();
                Ext.getCmp('loggedLabel').setHtml('Ya estas logeado como: '+tienda.getAt(0).data.nombre);
            }else{
                logged.hide();
                initial.show();
            }

    }

});