/*
 * File: app/view/VuelosContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.VuelosContainer', {
    extend: 'Ext.Container',
    alias: 'widget.VuelosContainer',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.field.Text',
        'Ext.tab.Panel',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.plugin.PullRefresh'
    ],

    config: {
        height: '100%',
        hidden: true,
        id: 'VuelosContainer',
        width: '100%',
        layout: 'fit',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'topBar',
                itemId: 'topBar',
                width: '100%',
                items: [
                    {
                        xtype: 'button',
                        id: 'vuelosContainerHome',
                        iconCls: 'list',
                        text: ''
                    },
                    {
                        xtype: 'textfield',
                        docked: 'right',
                        id: 'txtFiltro'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                id: 'vuelosTabPanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Arribos',
                        id: 'vuelosPanelArribos',
                        items: [
                            {
                                xtype: 'list',
                                scrollable: {
                                    direction: 'vertical',
                                    scroller: {
                                        listeners: {
                                            scrollend: function(scroller, x, y) {
                                        if(y < 0){
                                        // y < 0 eso significa que el scroll fue vertical, hacia abajo.
                                        Aeropuerto.app.getController('Global').getArrivals("",1);
                                        }  
                                        }
                                        }
                                    }
                                },
                                docked: 'top',
                                height: '100%',
                                id: 'lstArribos',
                                width: '100%',
                                itemTpl: [
                                    '<div style=\'text-align: center;\'>{origen}<br>{fprogram} - {estadosp}</div>'
                                ],
                                scrollToTopOnRefresh: false,
                                store: 'Arribos',
                                plugins: [
                                    {
                                        type: 'pullrefresh'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Partidas',
                        height: '100%',
                        id: 'vuelosPartidas',
                        width: '100%',
                        items: [
                            {
                                xtype: 'list',
                                scrollable: {
                                    direction: 'vertical',
                                    scroller: {
                                        listeners: {
                                            scrollend: function(scroller, x, y) {
                                                                if(y < 0){
                                                                // y < 0 eso significa que el scroll fue vertical, hacia abajo.
                                                                Aeropuerto.app.getController('Global').getDepartures("",1);
                                                                }  
                                                    }
                                        }
                                    }
                                },
                                docked: 'top',
                                height: '100%',
                                id: 'lstPartidas',
                                width: '100%',
                                itemTpl: [
                                    '<div>{destino}<br>{fprogram} - {estadosp}</div>'
                                ],
                                store: 'Partidas',
                                plugins: [
                                    {
                                        type: 'pullrefresh'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onVuelosTabPanelActiveItemChange',
                event: 'activeitemchange',
                delegate: '#vuelosTabPanel'
            }
        ]
    },

    onVuelosTabPanelActiveItemChange: function(container, value, oldValue, eOpts) {
        /*
        Aeropuerto.app.getController('Global').checkConnection();
        if(value.itemId === 'vuelosArribos'){
            Aeropuerto.app.getController('Global').getArrivals('','0');
        }else{
            Aeropuerto.app.getController('Global').getDepartures('','0');
        }
        */
    },

    initialize: function() {
        this.callParent();
        Ext.getCmp('txtFiltro').setPlaceHolder(Ext.getStore('StringsStore').getAt(0).data.vuelos_filtro);

        Ext.getCmp('vuelosTabPanel').getTabBar().getAt(0).setTitle(Ext.getStore('StringsStore').getAt(0).data.vuelo_arribos);
        Ext.getCmp('vuelosTabPanel').getTabBar().getAt(1).setTitle(Ext.getStore('StringsStore').getAt(0).data.vuelo_partidas);
    }

});