/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'Vuelo',
        'Weather',
        'Strings',
        'Usuario'
    ],
    stores: [
        'Arribos',
        'Partidas',
        'Uuid',
        'Suscripciones',
        'MisVuelos',
        'WeatherStore',
        'StringsStore',
        'UsuarioStore'
    ],
    views: [
        'MainContainer',
        'UserContainer',
        'TaxiContainer'
    ],
    controllers: [
        'Global',
        'LogicController',
        'Usuarios',
        'Taxi'
    ],
    name: 'Aeropuerto',
    statusBarStyle: 'black-translucent',

    launch: function() {
        var store= Ext.getStore('Uuid');
        var logeado= Ext.getStore('UsuarioStore');
        if(store.getCount() === 0){
            var guid =  this.getApplication().getController('LogicController').createUuid();

            var uuid = guid();
            store.add({key : uuid});
        }

        this.getApplication().getController('Global').getVersion('esp');
        this.getApplication().getController('Global').getArrivals('','0');

        //var DeviceLanguage = Locale.getDefault().getDisplayLanguage();
        //alert(DeviceLanguage);
        Ext.create('Aeropuerto.view.MainContainer', {fullscreen: true});
    }

});
