/*
 * File: app/store/MisVuelos.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.store.MisVuelos', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.LocalStorage',
        'Ext.data.Field'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        storeId: 'MisVuelos',
        proxy: {
            type: 'localstorage'
        },
        fields: [
            {
                name: 'nVuelo',
                type: 'string'
            },
            {
                name: 'fprogram',
                type: 'string'
            }
        ]
    }
});