/*
 * File: app/view/Arrivals.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.Arrivals', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Label'
    ],

    config: {
        id: 'arrivals',
        itemId: 'arrivals',
        style: '-webkit-transform: translate3d(0, 0, 0);   transform: translate3d(0, 0, 0);   transition: all 0.2s; ',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Arrivals',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'btnMenuArrivals',
                        iconCls: 'action',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'label',
                centered: true,
                html: 'Arrivals'
            }
        ]
    }

});