/*
 * File: app/view/EstacionamientoContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.EstacionamientoContainer', {
    extend: 'Ext.Container',
    alias: 'widget.estacionamientocontainer',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.tab.Panel',
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Label',
        'Ext.field.Checkbox',
        'Ext.picker.Slot'
    ],

    config: {
        height: '100%',
        hidden: true,
        id: 'EstacionamientoContainer',
        width: '100%',
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                id: 'estacionamientoToolbar',
                items: [
                    {
                        xtype: 'button',
                        id: 'estacionamientoContainerHome',
                        iconCls: 'list'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                id: 'estacionamientoTabPanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Solicitar Estacionamiento',
                        id: 'tabEstacionamientoSolicitar',
                        scrollable: 'vertical',
                        items: [
                            {
                                xtype: 'fieldset',
                                id: 'estacionamientoForm',
                                items: [
                                    {
                                        xtype: 'datepickerfield',
                                        id: 'estacionamientoDatePicker',
                                        margin: 20,
                                        padding: 8,
                                        label: 'Fecha',
                                        name: 'estacionamientoDatePicker',
                                        placeHolder: 'mm/dd/yyyy',
                                        displayField: 'Fecha',
                                        dateFormat: 'd/m/Y',
                                        picker: {
                                            useTitles: true,
                                            slotOrder: [
                                                'day',
                                                'month',
                                                'year'
                                            ]
                                        }
                                    },
                                    {
                                        xtype: 'container',
                                        id: 'horaComienzo',
                                        padding: 8,
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'Hora comienzo 00:00 AM',
                                                id: 'lblHoraComienzo',
                                                margin: 10,
                                                padding: 5,
                                                width: '100%'
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'seleccionarHoraComienzo',
                                                margin: 20,
                                                padding: 8,
                                                text: 'seleccionar hora'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        id: 'timpoReservar',
                                        padding: 8,
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'Tiempo a reservar 00:00 horas',
                                                id: 'lblTiempoReserva',
                                                margin: 10,
                                                padding: 5,
                                                width: '100%'
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'seleccionarTiempoReserva',
                                                margin: 20,
                                                padding: 8,
                                                text: 'seleccionar hora'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'estacionamientoMatricula',
                                        margin: 20,
                                        label: 'Matricula',
                                        name: 'estacionamientoMatricula'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'estacionamientoMarca',
                                        margin: 20,
                                        label: 'Marca',
                                        name: 'estacionamientoMarca'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'estacionamientoModelo',
                                        margin: 20,
                                        label: 'Modelo',
                                        name: 'estacionamientoModelo'
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'btnEstacionamientoContinuar',
                                        margin: 20,
                                        padding: 8,
                                        text: 'Continuar'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                hidden: true,
                                id: 'confirmarEstacionamientoForm',
                                items: [
                                    {
                                        xtype: 'label',
                                        html: 'El precio del servicio es : ',
                                        id: 'estacionamientoPrecioServicio',
                                        margin: 20
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        id: 'estacionamientoTerminos',
                                        margin: 20,
                                        label: 'Aceptar terminos y condiciones'
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'estacionamientoConfirmar',
                                        margin: 20,
                                        text: 'Aceptar'
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'estacionamientoCancelar',
                                        text: 'Cancelar'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Informacion',
                        id: 'tabEstacionamientoInformacion',
                        scrollable: 'vertical',
                        items: [
                            {
                                xtype: 'label',
                                id: 'lblInfoEstacionamiento',
                                margin: 20,
                                padding: 8
                            }
                        ]
                    },
                    {
                        xtype: 'picker',
                        hidden: true,
                        id: 'EstacionamientoHoraPicker',
                        itemId: 'mypicker2',
                        useTitles: true,
                        slots: [
                            {
                                xtype: 'pickerslot',
                                id: 'EstacionamientoHoras',
                                style: '  text-align: center;',
                                deselectOnContainerClick: false,
                                name: 'horas'
                            },
                            {
                                xtype: 'pickerslot',
                                id: 'EstacionamientoMinutos',
                                style: '  text-align: center;',
                                align: 'center',
                                name: 'minutos',
                                title: 'minutos'
                            },
                            {
                                xtype: 'pickerslot',
                                data: [
                                    {
                                        text: 'AM',
                                        value: 'AM'
                                    },
                                    {
                                        text: 'PM',
                                        value: 'PM'
                                    }
                                ],
                                id: 'EstacionamientoAPM',
                                style: '  text-align: center;',
                                align: 'right',
                                name: 'am',
                                title: 'am'
                            }
                        ]
                    },
                    {
                        xtype: 'picker',
                        hidden: true,
                        id: 'EstacionamientoReservarHora',
                        itemId: 'mypicker3',
                        useTitles: true,
                        slots: [
                            {
                                xtype: 'pickerslot',
                                id: 'estacionamientoReservarHoras',
                                style: '  text-align: center;',
                                deselectOnContainerClick: false,
                                name: 'horas'
                            },
                            {
                                xtype: 'pickerslot',
                                id: 'estacionamientoReservarMinutos',
                                style: '  text-align: center;',
                                align: 'center',
                                name: 'minutos',
                                title: 'minutos'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onEstacionamientoHoraPickerChange',
                event: 'change',
                delegate: '#EstacionamientoHoraPicker'
            },
            {
                fn: 'onEstacionamientoReservarHora',
                event: 'change',
                delegate: '#EstacionamientoReservarHora'
            }
        ]
    },

    onEstacionamientoHoraPickerChange: function(picker, value, eOpts) {
        var minutos = value.minutos;
        if(minutos < 10){
            minutos = "0"+minutos;
        }

        Ext.getCmp('lblHoraComienzo').setHtml("Hora comienzo: "+value.horas+":"+minutos+"     " +value.am);
    },

    onEstacionamientoReservarHora: function(picker, value, eOpts) {
        var minutos = value.minutos;
        if(minutos < 10){
            minutos = "0"+minutos;
        }

        Ext.getCmp('lblTiempoReserva').setHtml("Tiempo de reserva: "+value.horas+":"+minutos);
    },

    initialize: function() {
        this.callParent();
        var strings = Ext.getStore('StringsStore');

        // Ext.getCmp('taxiCantPersonas').add();
        var horas = new Array(13);
        var minutos = new Array(10);


        for (i = 0; i < 13; i++) {
            horas[i] = { text: i,value: i};

        }
        var cont=0;
        for (i = 0; i < 60; i++) {
            if(cont<60){
                minutos[i] =    {
                    text: cont,
                    value: cont
                };
            }
            cont+=5;
        }

        var fecha = new Date();
        Ext.getCmp('estacionamientoDatePicker').getPicker().setYearFrom(fecha.getFullYear());
        Ext.getCmp('estacionamientoDatePicker').getPicker().setYearTo(fecha.getFullYear() + 5);

        Ext.getCmp('EstacionamientoHoras').setValue(7);

        Ext.getCmp('EstacionamientoHoras').setData(horas);
        Ext.getCmp('EstacionamientoMinutos').setData(minutos);
        Ext.getCmp('estacionamientoReservarHoras').setData(horas);
        Ext.getCmp('estacionamientoReservarMinutos').setData(minutos);

        Ext.getCmp('estacionamientoDatePicker').setLabel(Ext.getStore('StringsStore').getAt(0).data.lavados_fecha);
        Ext.getCmp('estacionamientoMatricula').setLabel(Ext.getStore('StringsStore').getAt(0).data.lavados_matricula);
        Ext.getCmp('estacionamientoMarca').setLabel(Ext.getStore('StringsStore').getAt(0).data.lavados_marca);
        Ext.getCmp('estacionamientoModelo').setLabel(Ext.getStore('StringsStore').getAt(0).data.lavados_modelo);
        Ext.getCmp('btnEstacionamientoContinuar').setText(Ext.getStore('StringsStore').getAt(0).data.lavados_continuar);

        Ext.getCmp('seleccionarHoraComienzo').setText(Ext.getStore('StringsStore').getAt(0).data.lavado_seleccionarHora);

        //seleccionarTiempoReserva
        Ext.getCmp('estacionamientoTerminos').setLabel(Ext.getStore('StringsStore').getAt(0).data.lavados_terminos);

        Ext.getCmp('estacionamientoConfirmar').setText(Ext.getStore('StringsStore').getAt(0).data.global_aceptar);
        Ext.getCmp('estacionamientoCancelar').setText(Ext.getStore('StringsStore').getAt(0).data.global_cancelar);
        //Ext.getCmp('lblInfoEstacionamiento').setHtml(Ext.getStore('StringsStore').getAt(0).data.estacionamiento_informacion);


        //Ext.getCmp('estacionamientoTabPanel').getTabBar().getAt(0).setTitle(Ext.getStore('StringsStore').getAt(0).data.vuelo_arribos);
        Ext.getCmp('estacionamientoTabPanel').getTabBar().getAt(1).setTitle(Ext.getStore('StringsStore').getAt(0).data.global_informacion);

        Ext.getCmp('estacionamientoToolbar').setTitle(Ext.getStore('StringsStore').getAt(0).data.global_estacionamiento);

        Ext.getCmp('EstacionamientoHoras').setTitle('Horas');
        Ext.getCmp('EstacionamientoMinutos').setTitle('Minutos');
        Ext.getCmp('EstacionamientoAPM').setTitle('AM/PM');
        Ext.getCmp('estacionamientoReservarHoras').setTitle('Horas');
        Ext.getCmp('estacionamientoReservarMinutos').setTitle('Minutos');


    }

});