/*
 * File: app/view/HomeContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.HomeContainer', {
    extend: 'Ext.Container',
    alias: 'widget.HomeContainer',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.field.Text'
    ],

    config: {
        id: 'HomeContainer',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                id: 'HomeToolbar',
                items: [
                    {
                        xtype: 'button',
                        id: 'homeContainerHome',
                        iconCls: 'list'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'homeContainerSubs',
                        iconCls: 'organize'
                    }
                ]
            },
            {
                xtype: 'textfield',
                id: 'homeBuscarVuelos',
                margin: 20,
                padding: 8,
                label: 'Mi vuelo'
            },
            {
                xtype: 'button',
                id: 'homeButtonBuscar',
                margin: 20,
                padding: 8,
                text: 'Buscar Vuelo'
            }
        ]
    }

});