/*
 * File: app/view/MainContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.MainContainer', {
    extend: 'Ext.Container',
    alias: 'widget.mainContainer',

    requires: [
        'Ext.Panel',
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.field.Text',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.plugin.PullRefresh',
        'Ext.Toolbar',
        'Ext.Spacer'
    ],

    config: {
        id: 'mainContainer',
        itemId: '',
        top: '',
        items: [
            {
                xtype: 'panel',
                height: '100%',
                hideAnimation: '',
                id: 'mainView',
                itemId: '',
                margin: '',
                showAnimation: '',
                style: 'margin-top:2%;',
                width: '100%',
                listeners: [
                    {
                        fn: function(component, eOpts) {

                            this.element.on({
                                swipe: function(e, node, options) {
                                    if(e.direction == "left") {
                                        Aeropuerto.app.getController('LogicController').showHideMenu("left");
                                    }
                                    if(e.direction == "right") {
                                        Aeropuerto.app.getController('LogicController').showHideMenu("right");
                                    }
                                }
                            });

                            var items = [

                            {
                                xtype: 'button',
                                id: 'btnArribos',
                                text: 'Arribos',
                                iconCls: 'user',
                                cls: 'menu-button'
                            },
                            {
                                xtype: 'button',
                                id: 'btnPartidas',
                                text: 'Partidas',
                                iconCls: 'user',
                                cls: 'menu-button'
                            },
                            {
                                xtype: 'button',
                                id: 'btnSubscriptions',
                                text: 'Suscripciones',
                                iconCls: 'user',
                                cls: 'menu-button'
                            }

                            ];

                            Ext.Viewport.setMenu(Ext.create('Ext.Menu', {
                                style: 'padding: 15px;margin-top:2%;',
                                id: 'menu',
                                width: '60%',
                                items: items
                            }),{side: 'left',reveal: true});
                            },
                        event: 'initialize'
                    }
                ],
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        id: 'topBar',
                        itemId: 'topBar',
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnMenu',
                                iconCls: 'list',
                                text: ''
                            },
                            {
                                xtype: 'textfield',
                                docked: 'right',
                                id: 'txtFiltro',
                                label: ''
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        scrollable: {
                            direction: 'vertical',
                            scroller: {
                                listeners: {
                                    scrollend: function(scroller, x, y) {
                                if(y < 0){
                                // y < 0 eso significa que el scroll fue vertical, hacia abajo.
                                Aeropuerto.app.getController('Global').getArrivals("",1);
                                }  
                                }
                                }
                            }
                        },
                        docked: 'top',
                        height: '100%',
                        id: 'lstArribos',
                        width: '100%',
                        itemTpl: [
                            '<div>{origen}<br>{fprogram} - {estadosp}</div>'
                        ],
                        scrollToTopOnRefresh: false,
                        store: 'Arribos',
                        plugins: [
                            {
                                type: 'pullrefresh'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        scrollable: {
                            direction: 'vertical',
                            scroller: {
                                listeners: {
                                    scrollend: function(scroller, x, y) {
                                                        if(y < 0){
                                                        // y < 0 eso significa que el scroll fue vertical, hacia abajo.
                                                        Aeropuerto.app.getController('Global').getDepartures("",1);
                                                        }  
                                            }
                                }
                            }
                        },
                        docked: 'top',
                        height: '100%',
                        hidden: true,
                        id: 'lstPartidas',
                        width: '100%',
                        itemTpl: [
                            '<div>{destino}<br>{fprogram} - {estadosp}</div>'
                        ],
                        store: 'Partidas',
                        plugins: [
                            {
                                type: 'pullrefresh'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        height: '100%',
                        hidden: true,
                        id: 'lstSubscriptions',
                        width: '100%',
                        itemTpl: [
                            '<div>{aerolinea}<br>{nVuelo} - {estadosp}</div>'
                        ],
                        store: 'Suscripciones'
                    }
                ]
            },
            {
                xtype: 'panel',
                height: '100%',
                hidden: true,
                hideAnimation: '',
                id: 'details',
                itemId: 'mypanel1',
                showAnimation: '',
                width: '100%',
                listeners: [
                    {
                        fn: function(component, eOpts) {
                            this.element.on({
                                swipe: function(e, node, options) {
                                    if(e.direction == "right") {
                                        Aeropuerto.app.getController('LogicController').onDetailsBackButtonTap();
                                    }
                                }
                            });

                        },
                        event: 'initialize'
                    }
                ],
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        id: 'tbDetails',
                        title: 'Vuelo',
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnDetailsBack',
                                iconCls: 'arrow_left'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                id: 'btnDetailsSubscribe',
                                iconCls: 'favorites'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        centered: true,
                        height: '100%',
                        id: 'flightDetails',
                        width: '50%',
                        items: [
                            {
                                xtype: 'container',
                                height: '100%',
                                id: 'companyName',
                                tpl: [
                                    '"<h2>{nVuelo}</h2>",',
                                    '                                            "<h2>{aerolinea}</h2>",',
                                    '                                            "<h2>{origen}</h2>"',
                                    '<img style="height: 100px; width: 100px;" src="Img/Aeromas.png" />'
                                ],
                                width: '100%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: '100%',
                        id: 'weather',
                        tpl: [
                            '<h2>{temp_C}</h2>       <img style="height: 100px; width: 100px;" src={weatherIconUrl} />'
                        ],
                        width: '50%'
                    }
                ]
            }
        ]
    }

});