/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.MyContainer', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.TitleBar'
    ],

    config: {
        layout: 'hbox',
        items: [
            {
                xtype: 'container',
                hidden: true,
                id: 'navigation',
                style: 'background:black;',
                width: '20%',
                layout: 'card',
                items: [
                    {
                        xtype: 'button',
                        docked: 'top',
                        height: 60,
                        itemId: 'btnArrivals',
                        margin: '',
                        text: 'Arrivals'
                    },
                    {
                        xtype: 'button',
                        height: 60,
                        itemId: 'btnDepartures',
                        padding: '',
                        text: 'Departures'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'slide',
                height: '100%',
                id: 'main',
                width: '100%',
                zIndex: 5,
                layout: 'card',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        id: 'main-toolbar',
                        ui: 'light',
                        title: 'Main',
                        items: [
                            {
                                xtype: 'button',
                                id: 'mybutton',
                                itemId: 'mybutton4',
                                iconCls: 'locate',
                                text: ''
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        docked: 'top',
                        height: '100%',
                        id: 'lstArribos',
                        width: '100%',
                        itemTpl: [
                            '<div>{origen}<br>{fprogram} - {estadosp}</div>'
                        ],
                        store: 'Arribos'
                    },
                    {
                        xtype: 'list',
                        docked: 'top',
                        height: '100%',
                        hidden: true,
                        id: 'lstPartidas',
                        styleHtmlContent: true,
                        width: '100%',
                        itemTpl: [
                            '                          <div>{destino}<br>{fprogram} - {estadosp}</div>',
                            ''
                        ],
                        store: 'Partidas'
                    }
                ]
            },
            {
                xtype: 'container',
                height: '100%',
                hidden: true,
                id: 'details',
                width: '100%',
                zIndex: 10,
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        id: 'titleBarDetails',
                        title: 'Vuelo',
                        items: [
                            {
                                xtype: 'button',
                                docked: 'left',
                                id: 'btnBackDetals',
                                iconCls: 'arrow_left'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        centered: true,
                        id: 'info',
                        items: [
                            {
                                xtype: 'container',
                                centered: false,
                                id: 'photo',
                                tpl: [
                                    '<h2>{nVuelo}</h2>',
                                    '<h2>{aerolinea}</h2>',
                                    '<h2>{origen}</h2>'
                                ]
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#mybutton'
            }
        ]
    },

    onMybuttonTap: function(button, e, eOpts) {
        var c = Ext.getCmp('navigation');
        if(c === undefined){
            c = Ext.create('Aeropuerto.view.Navigation');
            Ext.Viewport.add(c);
        }


        //Ext.Viewport.setActiveItem(c);c.hide({type: 'slideOut', direction: 'left', duration: 70});

        if (Ext.getCmp('navigation').isHidden()) {
                    Ext.getCmp('navigation').show({type: 'slideIn', direction: 'right', duration: 70});
                }else {
                    Ext.getCmp('navigation').hide({type: 'slideOut', direction: 'left', duration: 70});
                }

        /*
                var main = Ext.get('main');


                if (main.hasCls('out')) {
                    main.removeCls('out');
                    main.addCls('in');
                    button.setText('Open');
                } else {
                    main.removeCls('in');
                    main.addCls('out');
                    button.setText('Close');
                }
        */
    }

});