/*
 * File: app/view/NormasContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.NormasContainer', {
    extend: 'Ext.Container',
    alias: 'widget.normascontainer',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        height: '100%',
        hidden: true,
        id: 'NormasContainer',
        width: '100%',
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                id: 'normasToolbar',
                items: [
                    {
                        xtype: 'button',
                        id: 'normasContainerHome',
                        iconCls: 'list'
                    }
                ]
            },
            {
                xtype: 'list',
                id: 'normasLista',
                itemTpl: [
                    '<div>{nombre}{ubicacion}</div>'
                ],
                grouped: true
            }
        ]
    },

    initialize: function() {
        this.callParent();

        Ext.getCmp('normasToolbar').setTitle(Ext.getStore('StringsStore').getAt(0).data.global_normativas);
    }

});