/*
 * File: app/view/SuscripcionesContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.SuscripcionesContainer', {
    extend: 'Ext.Container',
    alias: 'widget.suscripcionescontainer',

    requires: [
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        height: '100%',
        hidden: true,
        id: 'SuscripcionesContainer',
        width: '100%',
        layout: 'fit',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'topBar1',
                itemId: 'topBar1',
                items: [
                    {
                        xtype: 'button',
                        id: 'suscripcionesContainerHome',
                        iconCls: 'list',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'list',
                height: '100%',
                id: 'lstSubscriptions',
                width: '100%',
                itemTpl: [
                    '<div>{aerolinea}<br>{nVuelo} - {estadosp}</div>'
                ],
                store: 'Suscripciones'
            }
        ]
    }

});