/*
 * File: app/view/TimePickerField.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.TimePickerField', {
    extend: 'Ext.field.Text',
    alias: 'widget.timepickerfield',

    statics: {
        constructor: function(config) {
            // We're going to start by making string values of all of the times.

            var i,
                data_hours = [],
                data_minuts = [],
                data_AMPM = [],
                //stringVal,
                that = this;
            for(i=1; i<13; i++) {
                data_hours.push({
                    text: i,
                    value: i
                });
            }
            data_minuts.push({
                text: '00',
                value: '00'
            });
            var val = 15;
            for(i=0; i<3; i++) {
                data_minuts.push({
                    text: val,
                    value: val
                });
                val = val + 15;
            }
            data_AMPM.push({
                text:'PM',
                value:'PM'
            });
            data_AMPM.push({
                text:'AM',
                value:'AM'
            });

            if(Ext.os.deviceType == 'Desktop')
            {
                data_hours.push({
                    text: '',
                    value: ''
                });
                data_minuts.push({
                    text: '',
                    value: ''
                });
                data_AMPM.push({
                    text:'',
                    value:''
                });
            }

            // Make the time picker...

            this.picker = Ext.create("Ext.Picker", {
                hidden: true,
                zIndex: 9999,
                slots: [{
                    name: "hours",
                    title: "Hours",
                    data: data_hours
                },
                {
                    name: "minuts",
                    title: "Minuts",
                    data: data_minuts
                },
                {
                    name: "AMPM",
                    title: "test",
                    data: data_AMPM
                }
                ],
                listeners: {
                    change: function (picker, values) {
                        that.setValue(values.hours+':'+values.minuts+' '+values.AMPM);
                    }
                }
            });
        }
    },

    config: {
        xtype: 'timepickerfield'
    }

});