/*
 * File: app/view/UserContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.UserContainer', {
    extend: 'Ext.Container',
    alias: 'widget.usercontainer',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Label'
    ],

    config: {
        height: '100%',
        hidden: true,
        id: 'userContainer',
        width: '100%',
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        id: 'userContainerHome',
                        iconCls: 'list'
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: false,
                id: 'initial',
                items: [
                    {
                        xtype: 'button',
                        id: 'btnLoginInicial',
                        margin: 20,
                        padding: 8,
                        text: 'Login'
                    },
                    {
                        xtype: 'button',
                        id: 'btnRegisterInicial',
                        margin: 20,
                        padding: 8,
                        text: 'Rergister'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                hidden: true,
                id: 'loginForm',
                title: 'Longin',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'loginUsername',
                        label: 'Username',
                        labelWidth: '40%',
                        name: 'username'
                    },
                    {
                        xtype: 'textfield',
                        id: 'loginPassword',
                        label: 'Password',
                        labelWidth: '40%',
                        name: 'password'
                    },
                    {
                        xtype: 'button',
                        id: 'trueLogin',
                        margin: 20,
                        padding: 8,
                        text: 'Login'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                hidden: true,
                id: 'registerForm',
                title: 'Register',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'registerName',
                        label: 'Nombre',
                        labelWidth: '40%',
                        name: 'nombre'
                    },
                    {
                        xtype: 'textfield',
                        id: 'registerLastName',
                        label: 'Apellido',
                        labelWidth: '40%',
                        name: 'apellido'
                    },
                    {
                        xtype: 'emailfield',
                        id: 'registerEmail',
                        label: 'Email',
                        labelWidth: '40%',
                        name: 'email',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'passwordfield',
                        id: 'registerPassword',
                        width: '',
                        label: 'Contresena',
                        labelWidth: '40%',
                        name: 'contrasena'
                    },
                    {
                        xtype: 'datepickerfield',
                        id: 'registerDate',
                        label: 'Field',
                        labelWidth: '40%',
                        placeHolder: 'dd/mm/yyyy',
                        displayField: 'Fecha Nacimiento',
                        dateFormat: 'd/m/Y',
                        picker: {
                            yearFrom: 1940
                        }
                    },
                    {
                        xtype: 'button',
                        id: 'btnRegister',
                        margin: 20,
                        padding: 8,
                        text: 'Login'
                    }
                ]
            },
            {
                xtype: 'panel',
                centered: true,
                height: '100%',
                hidden: true,
                id: 'Logged',
                width: '100%',
                items: [
                    {
                        xtype: 'label',
                        centered: false,
                        id: 'loggedLabel'
                    },
                    {
                        xtype: 'button',
                        centered: true,
                        id: 'btnLogOut',
                        text: 'logout'
                    }
                ]
            }
        ]
    }

});