/*
 * File: app/view/UserContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.view.UserContainer', {
    extend: 'Ext.Container',
    alias: 'widget.usercontainer',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Password',
        'Ext.field.Email',
        'Ext.field.DatePicker',
        'Ext.picker.Date'
    ],

    config: {
        height: '100%',
        hidden: true,
        id: 'userContainer',
        width: '100%',
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                id: 'userToolbar',
                items: [
                    {
                        xtype: 'button',
                        id: 'userContainerHome',
                        iconCls: 'list'
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'initial',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'btnLoginInicial',
                        margin: 20,
                        padding: 8,
                        text: 'Login'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                id: 'loginForm',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'loginUsername',
                        label: '',
                        labelWidth: '40%',
                        name: 'username'
                    },
                    {
                        xtype: 'passwordfield',
                        id: 'loginPassword',
                        labelWidth: '40%',
                        name: 'password'
                    },
                    {
                        xtype: 'button',
                        id: 'trueLogin',
                        margin: 20,
                        padding: 8,
                        text: 'Login'
                    },
                    {
                        xtype: 'button',
                        id: 'btnRegisterInicial',
                        margin: 20,
                        padding: 8,
                        text: 'Rergister'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                hidden: true,
                id: 'registerForm',
                items: [
                    {
                        xtype: 'emailfield',
                        id: 'registerEmail',
                        labelWidth: '40%',
                        name: 'email',
                        required: true,
                        requiredCls: 'x-form-required-field',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'textfield',
                        id: 'registerName',
                        labelWidth: '40%',
                        name: 'nombre',
                        required: true
                    },
                    {
                        xtype: 'textfield',
                        id: 'registerLastName',
                        labelWidth: '40%',
                        name: 'apellido'
                    },
                    {
                        xtype: 'passwordfield',
                        id: 'registerPassword',
                        width: '',
                        label: '',
                        labelWidth: '40%',
                        name: 'contrasena',
                        required: true,
                        requiredCls: 'x-field-required-field'
                    },
                    {
                        xtype: 'passwordfield',
                        hidden: true,
                        id: 'registerPassword2',
                        width: '',
                        label: '',
                        labelWidth: '40%',
                        name: 'contrasena'
                    },
                    {
                        xtype: 'datepickerfield',
                        html: '',
                        id: 'registerDate',
                        labelWidth: '40%',
                        placeHolder: 'dd/mm/yyyy',
                        displayField: 'Fecha Nacimiento',
                        dateFormat: 'd/m/Y',
                        picker: {
                            style: '  text-align: center;',
                            slotOrder: [
                                'day',
                                'month',
                                'year'
                            ],
                            yearFrom: 1940
                        }
                    },
                    {
                        xtype: 'button',
                        id: 'btnRegister',
                        margin: 20,
                        padding: 8,
                        text: 'Login'
                    },
                    {
                        xtype: 'button',
                        id: 'btnLogOut',
                        margin: 20,
                        padding: 8,
                        text: 'logout'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();
        this.element.on({
            swipe: function(e, node, options) {
                if(e.direction == "right") {
                    Aeropuerto.app.getController('LogicController').showHideMenu("right");
                }
                if(e.direction == "left") {
                    Aeropuerto.app.getController('LogicController').showHideMenu("left");
                }
            }
        });

        //Set labels with language
        Ext.getCmp('registerName').setLabel(Ext.getStore('StringsStore').getAt(0).data.usuario_nombre);
        Ext.getCmp('registerLastName').setLabel(Ext.getStore('StringsStore').getAt(0).data.usuario_apellido);
        Ext.getCmp('registerEmail').setLabel(Ext.getStore('StringsStore').getAt(0).data.usuario_email);
        Ext.getCmp('registerPassword').setLabel(Ext.getStore('StringsStore').getAt(0).data.usuario_password);
        Ext.getCmp('registerPassword2').setLabel(Ext.getStore('StringsStore').getAt(0).data.usuario_password);
        Ext.getCmp('registerDate').setLabel(Ext.getStore('StringsStore').getAt(0).data.usuario_fecha_nacimiento);
        Ext.getCmp('trueLogin').setText(Ext.getStore('StringsStore').getAt(0).data.usuario_iniciarSesion);
        Ext.getCmp('btnLoginInicial').setText(Ext.getStore('StringsStore').getAt(0).data.usuario_iniciarSesion);

        Ext.getCmp('loginUsername').setLabel(Ext.getStore('StringsStore').getAt(0).data.usuario_email);
        Ext.getCmp('loginPassword').setLabel(Ext.getStore('StringsStore').getAt(0).data.usuario_password);

        Ext.getCmp('btnLogOut').setText(Ext.getStore('StringsStore').getAt(0).data.usuario_cerrarSesion);

        Ext.getCmp('btnRegister').setText(Ext.getStore('StringsStore').getAt(0).data.usuario_registrarse);
        Ext.getCmp('btnRegisterInicial').setText(Ext.getStore('StringsStore').getAt(0).data.usuario_registrarse);

        Ext.getCmp('userToolbar').setTitle(Ext.getStore('StringsStore').getAt(0).data.global_usuario);

    }

});