/*
 * File: app/store/ServiciosStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.store.ServiciosStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Aeropuerto.model.Servicios',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Xml',
        'Ext.data.proxy.LocalStorage'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        groupField: 'categoria',
        model: 'Aeropuerto.model.Servicios',
        storeId: 'ServiciosStore',
        proxy: {
            type: 'ajax',
            type: 'localstorage',
            reader: {
                type: 'xml',
                record: 'Servicios'
            }
        }
    }
});