/*
 * File: app/model/Strings.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Aeropuerto.model.Strings', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'version'
            },
            {
                name: 'cultura'
            },
            {
                name: 'global_inicio'
            },
            {
                name: 'global_suscripciones'
            },
            {
                name: 'global_vuelos'
            },
            {
                name: 'global_servicios'
            },
            {
                name: 'global_mapa'
            },
            {
                name: 'global_normativas'
            },
            {
                name: 'global_vip'
            },
            {
                name: 'gobal_taxi'
            },
            {
                name: 'global_estacionamiento'
            },
            {
                name: 'global_lavados'
            },
            {
                name: 'global_usuario'
            },
            {
                name: 'global_contacto'
            },
            {
                name: 'global_cargando'
            },
            {
                name: 'global_informacion'
            },
            {
                name: 'global_cancelar'
            },
            {
                name: 'global_aceptar'
            },
            {
                name: 'vuelos_filtro'
            },
            {
                name: 'vuelos_buscar'
            },
            {
                name: 'vuelo_partidas'
            },
            {
                name: 'vuelo_arribos'
            },
            {
                name: 'vuelo_detalles'
            },
            {
                name: 'usuario_registrarse'
            },
            {
                name: 'usuario_iniciarSesion'
            },
            {
                name: 'usuario_cerrarSesion'
            },
            {
                name: 'usuario_nombre'
            },
            {
                name: 'usuario_apellido'
            },
            {
                name: 'usuario_email'
            },
            {
                name: 'usuario_password'
            },
            {
                name: 'usuario_fecha_nacimiento'
            },
            {
                name: 'usuario_creado'
            },
            {
                name: 'usuario_fallo'
            },
            {
                name: 'taxi_info'
            },
            {
                name: 'taxi_cantidadPersonas'
            },
            {
                name: 'taxi_Origen'
            },
            {
                name: 'taxi_Destino'
            },
            {
                name: 'taxi_Desde'
            },
            {
                name: 'taxi_Solicitar'
            },
            {
                name: 'lavados_info'
            },
            {
                name: 'lavados_solicitar'
            },
            {
                name: 'lavados_fecha'
            },
            {
                name: 'lavados_hora'
            },
            {
                name: 'lavados_matricula'
            },
            {
                name: 'lavados_modelo'
            },
            {
                name: 'lavados_marca'
            },
            {
                name: 'lavados_continuar'
            },
            {
                name: 'lavados_costo'
            },
            {
                name: 'lavados_aceptarTerminos'
            },
            {
                name: 'lavados_terminos'
            },
            {
                name: 'lavados_mensajeError'
            },
            {
                name: 'usuario_modificarDatos'
            },
            {
                name: 'usuario_modificado'
            },
            {
                name: 'usuario_modificadoFallo'
            },
            {
                name: 'usuario_creadoFallo'
            },
            {
                name: 'global_fallo'
            },
            {
                name: 'usuario_passwordError'
            },
            {
                name: 'suario_loginIncorrecto'
            },
            {
                name: 'global_logToContinue'
            },
            {
                name: 'lavado_seleccionarHora'
            },
            {
                name: 'lavado_horaComienzo'
            },
            {
                name: 'lavado_solicitadoConExito'
            },
            {
                name: 'global_cancelarConfirmado'
            },
            {
                name: 'vuelo_noHaySuscripciones'
            }
        ]
    }
});